server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 192.168.159.135:9092
    # 生产者
    producer:
      acks: 1
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0
mq:
  kafka:
    topic: topic
    partition: 3
    replica: 1

#logging:
#  level:
#    org:
#      springframework:
#        kafka: trace
